# matplotlib

In [ ]:
import matplotlib.pyplot as plt

plt.plot([1,2,3],[4,5,6])
plt.show()

In [ ]:
from matplotlib import pyplot as plt
x=range(1,8)#x轴的位置
y=[17,17,18,15,11,11,13]
#传入x和y,通过plot画折线图
plt.plot(x,y)
plt.show()

In [ ]:
# 设置图片大小和保存
from matplotlib import pyplot as plt
import random
x=range(2,26,2)#x轴的位置
y=[random.randint(15,30)for i in x]
#设置图片的大小
'''
figsize:指定figure的宽和高，单位为英寸；
dpi参数指定绘图对象的分辨率，即每英寸多少个像素，缺省值为80，1英寸等于2.5cm,A4纸是21*30cm的纸张
'''
#设置画布对象，figsize中对应的单位是英寸，dpi是每英寸有多少像素点
plt.figure(figsize=(20,8),dpi=80)

plt.plot(x,y)#传入x和y,通过plot画图
#plt.show()
#保存(注意：要放在绘制的下面,并且plt.show()会释放figure资源，如果在显示图像之后保存图片将只能保存空图片。)
plt.savefig('./t1.png')
#图片的格式也可以保存为svg这种矢量图格式，这种矢量图放在网页中放大后不会有锯齿
#plt.savefig('./t1.svg')

In [ ]:
# 绘制x，y轴的刻度
from matplotlib import pyplot as plt
import random
x=range(2,26,2)#x轴的位置
y=[random.randint(15,30)for i in x]
plt.figure(figsize=(20,8),dpi=80)
plt.plot(x,y)
#设置x轴的刻度显示
plt.xticks(x)
#设置y轴的刻度显示
plt.yticks(range(10,35,5))
plt.show()

In [ ]:
# 设置中文显示
x=range(0,120)
y=[random.randint(10,30)for i in range(120)]
plt.figure(figsize=(20,8),dpi=80)
plt.plot(x,y)

#在有中文输出的地方，增加一个属性：fontproperties
plt.xlabel('时间',fontproperties='simHei',fontsize=20)

In [ ]:
# rotation将字体旋转一定的角度

plt.xticks(x[::10],rotation=45,fontproperties='simHei',fontsize=15)
plt.ylabel('温度',fontproperties='simHei',fontsize=20)
plt.title('未来一段时间的温度变化情况',fontproperties='simHei',fontsize=25)
plt.plot(x,y)

In [ ]:
# 一图多线绘制
y1=[1,0,1,1,2,4,3,4,4,5,6,5,4,3,3,1,1,1,1,1]
y2=[1,0,3,1,2,2,3,4,3,2,1,2,1,1,1,1,1,1,1,1]

x=range(11,31)
##设置图形
plt.figure(figsize=(20,8),dpi=80)

plt.plot(x,y1,color='red',label='自己')
plt.plot(x,y2,color='blue',label='同事')
#设置x轴刻度
xtick_labels=['{}岁'.format(i) for i in x]
plt.xticks(x,xtick_labels,fontproperties='simHei',fontsize=15,rotation=45)
#绘制网格（网格也是可以设置线的样式)
#alpha=0.4设置透明度
plt.grid(alpha=0.4)
# 添加图例,prop='simHei'设置图例的字体，loc='upper left'设置图例的位置，fontsize=15设置图例的字体大小
plt.legend(prop='simHei',loc='upper left',fontsize=15)
plt.show()

In [ ]:
# 一个图多个坐标系子图
import numpy as np
import matplotlib.pyplot as plt
x=np.arange(1,100)
#划分图像为2行2列的4个子图
fig,axes=plt.subplots(2,2,figsize=(20,10),dpi=80)
ax1=axes[0,0]
ax2=axes[0,1]
ax3=axes[1,0]
ax4=axes[1,1]
#作图1
ax1.plot(x,x)
#作图2
ax2.plot(x,-x)
#作图3
ax3.plot(x,x**2)
ax3.grid(color='r',linestyle='--',linewidth=1,alpha=0.3)
#作图4
ax4.plot(x,np.log(x))
plt.show()

In [ ]:
# 画散点图
y=[11,17,16,11,12,11,12,6,6,7,8,9,12,15,14,17,18,21,16,17,20,14,15,15,15,19,21,22,22,22,23]
x=range(1,32)
#设置图像大小
plt.figure(figsize=(20,8),dpi=80)
plt.scatter(x,y,label='三月份')
_xticks_labels=['3月{}日'.format(i)for i in x]
my_font='SimHei'
plt.xticks(x[::3],_xticks_labels[::3],fontproperties=my_font,rotation=45)
plt.xlabel('日期',fontproperties=my_font)
plt.ylabel('温度',fontproperties=my_font)
#图例
plt.legend(prop=my_font)
plt.show()

In [ ]:
# 绘制条形图
my_font='SimHei'
a=['流浪地球','疯狂的外星人','飞驰人生','大黄蜂','熊出没·原始时代','新喜剧之王']
b=[38.13,19.85,14.89,11.36,6.47,5.93]
#设置图像大小
plt.figure(figsize=(20,8),dpi=80)
#绘制条形图的方法
rects=plt.bar(range(len(a)),b,width=0.3,color='r')
plt.xticks(range(len(a)),a,fontproperties=my_font,rotation=45)
# 在条形图上显示数值
for rect in rects:
    height=rect.get_height()#获取条形图的高度
    plt.text(rect.get_x()+rect.get_width()/2,height+0.5,str(height),ha='center',va='bottom',fontproperties=my_font)
plt.show()

In [ ]:
# 绘制直方图
#生成90-180的250个随机数
time=[np.random.randint(90,180)for i in range(250)]
#设置图像大小
plt.figure(figsize=(20,8),dpi=80)
#设置组距
distance = 2
# 计算组数
group_num=int((max(time)-min(time))/distance)
#设置x轴的刻度显示
plt.xticks(range(min(time),max(time))[::2])
# 添加网格
plt.grid(linestyle="--",alpha=0.4)
#添加x,y轴描述信息
plt.xlabel("电影时长大小",fontproperties=my_font)
plt.ylabel("电影的数据量",fontproperties=my_font)
#绘制直方图
plt.hist(time,bins=group_num)
plt.show()

In [ ]:
# 绘制饼图
import matplotlib
label_list=["第一部分","第二部分","第三部分"]#各部分标签
size=[55,35,10]#各部分大小
color=["red","green","blue"]#各部分颜色
explode=[0,0.05,0]#各部分突出值

"""
绘制饼图
explode：设置各部分突出
label:设置各部分标签
labeldistance:设置标签文本距圆心位置，1.1表示1.1倍半径
autopct：设置圆里面文本
shadow：设置是否有阴影，立体感
startangle：起始角度，默认从0开始逆时针转
pctdistance：设置圆内文本距圆心距离返回值
l_text：圆内部文本，
matplotlib.text.Textobject
p_text：圆外部文本"""

matplotlib.rcParams['font.sans-serif']=['SimHei'] #设置中文显示
patches,l_text,p_text=plt.pie(size,explode=explode,colors=color,labels=label_list,
labeldistance=1.1,autopct="%1.1f%%",shadow=False,
startangle=90,pctdistance=0.6)
plt.axis("equal") #设置横轴和纵轴大小相等，这样饼才是圆的
plt.legend()#显示图例
plt.show()

# Numpy

## 列表转ndarray

In [ ]:
# 列表转ndarray
import numpy as np
a=[1,2,3,4,5]
b=np.array(a)
print(b)# 区别就是没有逗号分隔符

## ndarray与Python原生list运算效率对比

In [ ]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())
print('列表生成完成')

In [ ]:
t1 = time.time()
sum1 =sum(a)
t2 = time.time()
b = np.array(a)
t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(f'原生list用时{t2 - t1}, ndarray用时{t5 - t4}')


## numPy 的ndarray 对象

In [ ]:
# 创建一个一维数组
import numpy as np
# 直接传入一个列表
a = np.array([1, 2, 3, 4, 5])
# 2.传入range生成序列
b = np.array(range(1, 6))
# 3.使用numpy自带的np.arange()生成数组
c = np.arange(1, 6)
print(a)
print(b)
print(c)

In [ ]:
# 创建一个二维数组
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

In [ ]:
# 常用属性
list2= [[1,2],[3,4],[5,6]]
#获取数组的维度
a=np.array(list2)
print(a.ndim)
#获取数组的形状
print(a.shape)
#获取数组的元素个数
print(a.size)

In [ ]:
# 调整数组的形状
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
#调整为3行2列
b = a.reshape(3, 2)
print(b)
#调整为6行1列
c = a.reshape(6, 1)
print(c)
# 将多维数组调整为一维数组
#reshape和flatten都可以将多维数组调整为一维数组，但它们的行为略有不同。reshape返回一个新的视图，而flatten返回一个新的副本。
#order参数指定了元素在内存中的存储顺序，'C'表示按行优先，'F'表示按列优先。默认情况下，reshape使用'C'顺序。
d = a.reshape((6,),order='F')
#默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
e = a.flatten(order='F')
print(d)
print(e)

In [ ]:
# 数组转换为列表
a= np.array([[1, 2, 3], [4, 5, 6]])
b = a.tolist()
print(a)
print(b)

## numpy的数据类型

In [ ]:
#返回数组中每个元素的字节单位长度，dtype设置数据类型
f=np.array([1,2,3,4,5],dtype=np.int16)
print(f.itemsize)# 1 np.int8(一个字节)

#获取数据类型
print(f.dtype)
# 调整数据类型
g = f.astype(np.float32)
print(g.dtype)

# 随机生成小数
# python内置的random模块中的random()函数可以生成一个0到1之间的随机小数，左闭右开。保留两位
print(round(random.random(),2))

arr=np.array([random.random()for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))

## 数组的运算

In [ ]:
# 数组与标量的运算
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)
# 数组的每个元素都加上10
b = a + 10
print(b)
# 数组的每个元素都乘以2
c = a * 2
print(c)
# 数组的每个元素都除以2
d = a / 2
print(d)
# 数组的每个元素都减去1
e = a - 1
print(e)

In [ ]:
# 数组与数组的运算(同种类的数组之间可以进行运算，运算时会对数组中的每个元素进行相应的运算)
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
# 数组对应元素相加
c = a + b
print(c)
# 数组对应元素相减
d = b - a
print(d)
# 数组对应元素相乘
e = a * b
print(e)
# 数组对应元素相除
f = b / a
print(f)
print('*'*50)
# 不同形状的多维数组之间不能运算，行数或列数相同的一维数组和多维数组之间可以运算
# 当两个数组的形状不同时，NumPy会尝试进行广播来使它们具有相同的形状，从而进行运算。
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([10, 20, 30, 40])
# 当我们尝试将这两个数组相加时，NumPy会自动广播一维数组b，使其形状变为(1, 4)，然后再进行元素级的相加运算：
c = a + b
print(c)

In [ ]:
# 数组中的轴
import numpy as py
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a, axis=0))  # 沿着列的方向求和，结果是一个包含每列元素之和的一维数组
print(np.sum(a, axis=1))  # 沿着行的方向求和，结果是一个包含每行元素之和的一维数组
print(np.sum(a))

print('*'*50)
a=np.arange(27).reshape((3,3,3))
print(a)
print('*'*50)
print(np.sum(a,axis=0))# 沿着第0轴求和，结果是一个形状为(3, 3)的数组，其中每个元素是沿着第0轴（即最外层的轴）求和得到的结果。
print('*'*50)
print(np.sum(a,axis=1))# 沿着第1轴求和，结果是一个形状为(3, 3)的数组，其中每个元素是沿着第1轴（即中间的轴）求和得到的结果。
print('*'*50)
print(np.sum(a,axis=2))# 沿着第2轴求和，结果是一个形状为(3, 3)的数组，其中每个元素是沿着第2轴（即最内层的轴）求和得到的结果。
print('*'*50)

## 数组的切片与索引

In [ ]:
# 一维数组的切片与索引
# 冒号分隔切片参数 start:stop:step 来进行切片操作
import numpy as np
a = np.array([10, 20, 30, 40, 50])
# 访问最后一个元素
print(a[-1])
# 访问第2到第4个元素（不包括第4个元素）
print(a[1:4])
# 访问第1到第5个元素，步长为2
print(a[0:5:2])
# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2:],a)

In [ ]:
# 多维数组的切片与索引
import numpy as np
a =  np.arange(24).reshape(4,6)
print(a)
print('-'*50)
# 访问第2行第3列的元素
print(a[1, 2])
# 访问第1行的所有元素
print(a[0, :])
# 访问第2列的所有元素
print(a[:, 1])
# 访问第1行到第2行，第2列到第3列的子数组
print(a[0:2, 1:3])

## 数组中的元素修改

In [ ]:
# 数组中的数值修改
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('-'*50)
# 修改第1行第2列的元素为10
a[0, 1] = 10
print(a)
print('-'*50)
# 修改第2行的所有元素为20
a[1, :] = 20
print(a)
print('-'*50)
# 修改第1列的所有元素为30
a[:, 0] = 30
print(a)
print('-'*50)
# 连续修改多行
a[0:2, :] = 40
print(a)
print('-'*50)
# 连续修改多列
a[:, 0:2] = 50
print(a)
print('-'*50)
# 连续修改多行多列
a[0:2, 0:2] = 60
print(a)
print('-'*50)
# 根据条件修改
a[a > 50] = 70
print(a)
print('-'*50)
# 使用逻辑判断&,|,~来修改满足多个条件的元素
a[(a > 30) & (a < 60)] = 80
print(a)
print('-'*50)
a=a.clip(73,77)# 将数组中的元素限制在73和77之间，超过73的元素被替换为73，超过77的元素被替换为77
print(a)
print('-'*50)
 # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出 x，不满足输出y
score = np.array( [[80,88], [82,81], [75,81]] )
result = np.where( score >80,True,False)
print( result )

In [ ]:
# 数组的添加
#numpy函数在数组的末尾添加元素，返回一个新的数组，原数组不变
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print('向数组添加元素：')#添加元素时会将原数组展平为一维数组，然后在末尾添加元素，最后返回一个新的数组
print(np.append(a, [7,8,9]))
print('沿轴0添加元素：')#按列加，必须保证添加的元素的列数和原数组的列数相同
print(np.append(a, [[7,8,9]],axis=0))
print('沿轴1添加元素：')#按行加，必须保证添加的元素的行数和原数组的行数相同
print(np.append(a, [[5,5,5], [7,8,9]],axis=1))


In [ ]:
#数组中的删除
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print('删除第1行：')#删除第1行，axis=0表示按行删除
print(np.delete(a, 0, axis=0))
print('删除第2列：')#删除第2列，axis=1表示按列删除
print(np.delete(a, 1, axis=1))

In [ ]:
#数组去重
import numpy as np
a = np.array([1, 2, 3, 4, 5, 1, 2, 3])
print(a)
print(np.unique(a))
#去重数组的索引数组
print(np.unique(a, return_index=True))#返回去重后的数组和原数组中每个唯一值的第一个出现位置的索引数组
#去重元素的重复数量
print(np.unique(a, return_counts=True))#返回去重后的数组和每个唯一值在原数组中出现的次数的计数数组

## numpy的计算

In [ ]:
# 通用函数：
# numpy.sqrt(array)平方根函数
# numpy.exp(array)e^array[i]的数组
# numpy.abs/fabs(array)计算绝对值
# numpy.square(array)计算各元素的平方等于array2
# numpy.log/log10/log2(array)计算各元素的各种对数
# numpy.sign(array)计算各元素正负号
# numpy.isnan(array)计算各元素是否为NaN
# numpy.isinf(array)计算各元素是否为NaN
# numpy.cos/cosh/sin/sinh/tan/tanh(array)三角函数
# numpy.modf(array)将array中值得整数和小数分离，作两个数组返回
# numpy.ceil(array)向上取整,也就是取比这个数大的整数
# numpy.floor(array)向下取整,也就是取比这个数小的整数
# numpy.rint(array)四舍五入
# numpy.trunc(array)向0取整
# numpy.cos(array)正弦值
# numpy.sin(array)余弦值
# numpy.tan(array)正切值
# numpy.add(array1,array2)元素级加法
# numpy.subtract(array1,array2)元素级减法
# numpy.multiply(array1,array2)元素级乘法
# numpy.divide(array1,array2)元素级除法array1./array2
# numpy.power(array1,array2)元素级指数array1.^array2
# numpy.maximum/minimum(array1,aray2)元素级最大值
# numpy.fmax/fmin(array1,array2)元素级最大值，忽略NaN
# numpy.mod(array1,array2)元素级求模
# numpy.copysign(array1,array2)将第二个数组中值得符号复制给第一个数组中值
# numpy.greater/greater_equal/less/less_equal/equal/not_equal(array1,array2)
# 元素级比较运算，产生布尔数组
# numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算

In [73]:
# numpy的计算（数学函数）
import numpy as np
a = np.array([1, 2, 3, 4, 5])
# 计算数组的平方
print(np.square(a))
# 计算数组的平方根
print(np.round(np.sqrt(a),2))
# 计算数组的自然对数
print(np.round(np.log(a),2))
# 计算数组的指数
print(np.round(np.exp(a),2))
# 获取所有数的最大值
print(np.max(a))
# 获取一个轴上的最大值，对应轴会消失
print(np.max(a, axis=0))

[ 1  4  9 16 25]
[1.   1.41 1.73 2.   2.24]
[0.   0.69 1.1  1.39 1.61]
[  2.72   7.39  20.09  54.6  148.41]


## 数组的拼接与切割

In [4]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
#根据轴的不同进行拼接，axis=0表示按行拼接，axis=1表示按列拼接
print(np.concatenate((a, b), axis=0))#按行拼接
print(np.concatenate((a, b), axis=1))#按列拼接
print('-'*50)

#拼接不增加维度，堆叠先升维再拼接（按那个轴堆叠就会在那个轴上增加维度）
#根据轴进行堆叠
print(np.stack((a, b),axis=0))#按行堆叠
print(np.stack((a, b),axis=1))#按列堆叠
print('-'*50)

#矩阵垂直拼接
print(np.vstack((a, b)))#按行拼接
#矩阵水平拼接
print(np.hstack((a, b)))#按列拼接
print('-'*50)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------


In [6]:
# 数据的切割
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
# 将数组切割成两个子数组，axis=0表示按行切割，axis=1表示按列切割
print(np.split(a, 2, axis=0))#按行切割成两个子数组
print(np.split(a, 2, axis=1))#按列切割成两个子数组
print('-'*50)
# 将数组切割成不等长的子数组，axis=0表示按行切割，axis=1表示按列切割
print(np.split(a, [1, 3], axis=0))#按行切割成不等长的子数组，[1, 3]表示切割点的索引位置，切割点之前的元素为第一个子数组，切割点之后的元素为第二个子数组，切割点之后的元素为第三个子数组
print(np.split(a, [1, 3], axis=1))#按列切割成不等长的子数组，[1, 3]表示切割点的索引位置，切割点之前的元素为第一个子数组，切割点之后的元素为第二个子数组，切割点之后的元素为第三个子数组

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
--------------------------------------------------
[array([[1, 2]]), array([[3, 4],
       [5, 6]]), array([[7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int64)]


## 数组中的inf和NaN

In [1]:
# inf表示无穷大，NaN表示不是一个数字
import numpy as np
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))
# --判断数组中为 nan 的个数
t = np.arange(24,dtype=float).reshape(4,6)
# 将三行四列的数改成 nan
t[3,4] = np.nan
# 可以使用 np.count_nonzero() 来判断非零的个数
print(np.count_nonzero(t))
# 并 且np.nan != np.nan结果 是 TRUE
# 所以我们可以使用这两个结合使用判断 nan 的个数
print(t)
print(np.count_nonzero(t != t))
# 将 nan 替换为 0
t[np.isnan(t)] =0
print(t)
#Nan和任何值计算结果都是NaN
print(np.nan + 1)
# inf和inf相等
print(np.inf == np.inf)
print(np.inf+np.nan)
# nan会使运算速率变慢，inf会导致后续计算结果变成inf

nan <class 'float'>
inf <class 'float'>
23
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
1
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21.  0. 23.]]
nan
True
nan


## 数组的转置

In [6]:
# 对换数据的维度
import numpy as np
a = np.arange(12).reshape(3,4)
print('原数组：')
print(a)
print('\n')
print('对换数组：')
print(np.transpose(a))
print('转置数组：')
print(a.T)
print('-'*50)
# swapaxes函数可以交换数组的两个轴
t1 = np.arange(24).reshape(4,3,2)
print('原数组：')
print(t1.shape)
print('交换轴0和轴1的数组：')
a=np.swapaxes(t1, 0, 1)
print(a.shape)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------------------------------------
原数组：
(4, 3, 2)
交换轴0和轴1的数组：
(3, 4, 2)
(4, 3, 2)


In [7]:
# rollaxis函数可以将指定的轴滚动到给定的位置之前
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape# 将轴3滚动到轴1之前，结果的形状为(3, 6, 4, 5)

(3, 6, 4, 5)

## copy和view

In [8]:
# copy和view的区别
import numpy as np
a = np.array([1, 2, 3, 4, 5])
# 使用copy创建一个新的数组，修改新数组不会影响原数组
b = a.copy()
b[0] = 10
print('原数组：', a)
print('copy数组：', b)
print('-'*50)
# 使用view创建一个新的视图，修改新视图会影响原数组
c = a.view()
c[0] = 20
print('原数组：', a)
print('view数组：', c)

原数组： [1 2 3 4 5]
copy数组： [10  2  3  4  5]
--------------------------------------------------
原数组： [20  2  3  4  5]
view数组： [20  2  3  4  5]


In [1]:
#读文件提示找不到文件，执行下列代码：
import os
print(os.getcwd())#查看当前路径
#os.chdir('文件所在路径')#切换到文件所在路径

E:\Python_train


In [4]:
import pandas as pd

my_path = './pandas学习/911.csv'
data = pd.read_csv(my_path)

print(data.head())


         lat        lng                                               desc  \
0  40.297876 -75.581294  REINDEER CT & DEAD END;  NEW HANOVER; Station ...   
1  40.258061 -75.264680  BRIAR PATH & WHITEMARSH LN;  HATFIELD TOWNSHIP...   
2  40.121182 -75.351975  HAWS AVE; NORRISTOWN; 2015-12-10 @ 14:39:21-St...   
3  40.116153 -75.343513  AIRY ST & SWEDE ST;  NORRISTOWN; Station 308A;...   
4  40.251492 -75.603350  CHERRYWOOD CT & DEAD END;  LOWER POTTSGROVE; S...   

       zip                    title            timeStamp                twp  \
0  19525.0   EMS: BACK PAINS/INJURY  2015-12-10 17:10:52        NEW HANOVER   
1  19446.0  EMS: DIABETIC EMERGENCY  2015-12-10 17:29:21  HATFIELD TOWNSHIP   
2  19401.0      Fire: GAS-ODOR/LEAK  2015-12-10 14:39:21         NORRISTOWN   
3  19401.0   EMS: CARDIAC EMERGENCY  2015-12-10 16:47:36         NORRISTOWN   
4      NaN           EMS: DIZZINESS  2015-12-10 16:56:52   LOWER POTTSGROVE   

                         addr  e  
0      REINDEER CT & 